# Jenkins Sandbox
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-sandbox
    privileged: true
    user: root
    ports:
      - 8091:8080
      - 50000:50000
    volumes:
      - /opt/jenkins/home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_nw
  agent:
    image: jenkins/ssh-agent:jdk11
    container_name: jenkins-sandbox-agent
    privileged: true
    user: root
    expose:
      - 22
    networks:
      - jenkins_nw
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
  rustagent:
    image: rustmeup
    container_name: jenkins-sandbox-rustagent
    privileged: true
    user: root
    expose:
      - 22
    volumes:
      - /opt/jenkins/home:/opt/rust/workspace
        #- /opt/jenkins/rust_home:/opt/rust/workspace
    networks:
      - jenkins_nw
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
networks:
  jenkins_nw:
    external: true
