# For DataNode setup, graylog starts with a preflight UI, this is a change from just using OpenSearch/Elasticsearch.
# Please take a look at the README at the top of this repo or the regular docs for more info.

services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: "mongodb-raspberrypi4-unofficial-r7.0.4:latest"
    restart: "on-failure"
    networks:
      - graylog_nw
    ports:
      - "0.0.0.0:27017:27017/tcp"
    volumes:
      - "/opt/graylog/mongodb_data:/data/db"
      - "/opt/graylog/mongodb_config:/data/configdb"


  # For DataNode setup, graylog starts with a preflight UI, this is a change from just using OpenSearch/Elasticsearch.
  # Please take a look at the README at the top of this repo or the regular docs for more info.
  # Graylog Data Node: https://hub.docker.com/r/graylog/graylog-datanode

  # ⚠️ Make sure this is set on the host before starting:
  # echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
  # sudo sysctl -p
  datanode:
    image: "graylog/graylog-datanode:7.0.4"
    hostname: "datanode"
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      # GRAYLOG_DATANODE_PASSWORD_SECRET and GRAYLOG_PASSWORD_SECRET MUST be the same value
      GRAYLOG_DATANODE_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "0.0.0.0:8999:8999/tcp"   # DataNode API
      - "0.0.0.0:9200:9200/tcp"
      - "0.0.0.0:9300:9300/tcp"
    networks:
      - graylog_nw
    volumes:
      - "/opt/graylog/graylog-datanode:/var/lib/graylog-datanode"
    restart: "on-failure"


  # Graylog: https://hub.docker.com/r/graylog/graylog-enterprise
  graylog:
    hostname: "server"
    image: "graylog/graylog:7.0.4"
    depends_on:
      mongodb:
        condition: "service_started"
      datanode:
        condition: "service_started"
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      # GRAYLOG_DATANODE_PASSWORD_SECRET and GRAYLOG_PASSWORD_SECRET MUST be the same value
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      #GRAYLOG_HTTP_EXTERNAL_URI: "{{ salt['pillar.get']('graylog_allowed_origins') }}/"
      #GRAYLOG_HTTP_PUBLISH_URI: "{{ salt['pillar.get']('graylog_allowed_origins') }}/"
      #GRAYLOG_HTTP_PUBLISH_URI: "http://localhost:9000/"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
    - "0.0.0.0:5044:5044/tcp"   # Beats
    - "0.0.0.0:5140:5140/udp"   # Syslog
    - "0.0.0.0:5140:5140/tcp"   # Syslog
    - "0.0.0.0:5555:5555/tcp"   # RAW TCP
    - "0.0.0.0:5555:5555/udp"   # RAW UDP
    - "0.0.0.0:12201:12201/tcp" # GELF TCP
    - "0.0.0.0:12201:12201/udp" # GELF UDP
    - "0.0.0.0:13301:13301/tcp" # Forwarder data
    - "0.0.0.0:13302:13302/tcp" # Forwarder config
    - "0.0.0.0:9000:9000/tcp"   # Server API
    #- "0.0.0.0:1514:514/tcp" # SYSLOG
    #- "0.0.0.0:1514:514/udp" # SYSLOG
    networks:
      - graylog_nw
    volumes:
      - "/opt/graylog/graylog_data:/usr/share/graylog/data/data"
    restart: "on-failure"

networks:
  graylog_nw:
    driver: "bridge"

volumes:
  mongodb_data:
  mongodb_config:
  graylog-datanode:
  graylog_data:
